# Generated by Django 5.2.16 on 2026-07-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Користувач'), ('moderator', 'Модератор'), ('admin', 'Адміністратор')], default='user', max_length=20, verbose_name='Роль'),
        ),
    ]
